#version 440

layout(set=0, binding=0, rgba8) uniform image2D sceneImage;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main(){

    if(any(greaterThanEqual(gl_GlobalInvocationID.xy, imageSize(sceneImage)))){
        return;
    }
    ivec2 uv = ivec2(gl_GlobalInvocationID.xy);
    vec3 linearColor = imageLoad(sceneImage, uv).rgb;
    vec3 gammaCorrected = pow(linearColor, vec3(1.f / 2.2f));
    imageStore(sceneImage, uv, vec4(gammaCorrected, 0.f));
}