variables:
  RUN:
    value: "win"
    description: "The tests that should run. Possible values: ubuntu, win, all."
  GIT_DEPTH: 1

stages:
  - build
  - deploy

build_ubuntu_gcc:
  only:
    variables:
      - $RUN =~ /\bubuntu.*/i || $RUN =~ /\ball.*/i
  stage: build
  tags: 
    - ubuntu-gcc
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  timeout: 10m
  retry: 1
  script:
    - mkdir debug
    - cd debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build .
  artifacts:
    name: "Documentation - $CI_PIPELINE_ID"
    paths:
      - doc/html
      - doc/latex
    expire_in: never

build_win10_msvc:
  only:
    variables:
      - $RUN =~ /\bwin.*/i || $RUN =~ /\ball.*/i
  stage: build
  tags: 
    - win10-msvc
    - with-cache
  variables:
    GIT_STRATEGY: none
  timeout: 10m
  retry: 0
  script:
    - cd 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\'
    - .\Launch-VsDevShell.ps1
    - cd C:\cached\vkcv-framework
    - ls ~/.ssh/
    - git fetch
    - git checkout $CI_COMMIT_SHA
    - git pull
    - git submodule init
    - git submodule update
    - mkdir debug
    - cd debug
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - cmake --build .

deploy_doc_develop:
  only:
    variables:
      - $RUN =~ /\bubuntu.*/i || $RUN =~ /\ball.*/i
    refs:
      - develop
  stage: deploy
  needs: ["build_ubuntu_gcc"]
  dependencies: 
    - build_ubuntu_gcc
  tags: 
    - webserver
  variables:
    GIT_STRATEGY: none
  script:
    - rsync -avh doc/html/ /var/www/html/develop --delete
    - echo "Check it out at https://vkcv.de/develop"

deploy_doc_branch:
  only:
    variables:
      - $RUN =~ /\bubuntu.*/i || $RUN =~ /\ball.*/i
  except:
    refs:
      - develop
  stage: deploy
  needs: ["build_ubuntu_gcc"]
  dependencies: 
    - build_ubuntu_gcc
  tags: 
    - webserver
  variables:
    GIT_STRATEGY: none
  script:
    - rsync -avh  doc/html/ /var/www/html/branch/$CI_COMMIT_BRANCH --delete
    - echo "Check it out at https://vkcv.de/branch/$CI_COMMIT_BRANCH"