#version 440
#extension GL_GOOGLE_include_directive : enable

layout(set=0, binding=0, rgba32f) 	uniform image2D outImage;

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

void main(){

    ivec2 outImageRes = imageSize(outImage);
    ivec2 coord       = ivec2(gl_GlobalInvocationID.xy);

    if(any(greaterThanEqual(coord, outImageRes)))
        return;

    imageStore(outImage, coord, vec4(0));
}