#version 440
#extension GL_GOOGLE_include_directive : enable

layout(set=0, binding=0) buffer indirectArgumentBuffer {
    uint dispatchArgs[3];
};

layout( push_constant ) uniform constants{
    uint width;
    uint height;
};

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

void main(){

    dispatchArgs[0] = (width  + 7) / 8;
    dispatchArgs[1] = (height + 7) / 8;
    dispatchArgs[2] = 1;
}