#pragma once

namespace vkcv {

	enum class ShaderStage : VkShaderStageFlags
	{
		VERTEX = VK_SHADER_STAGE_VERTEX_BIT,
		TESS_CONTROL = VK_SHADER_STAGE_TESSELLATION_CONTROL_BIT,
		TESS_EVAL = VK_SHADER_STAGE_TESSELLATION_EVALUATION_BIT,
		GEOMETRY = VK_SHADER_STAGE_GEOMETRY_BIT,
		FRAGMENT = VK_SHADER_STAGE_FRAGMENT_BIT,
		COMPUTE = VK_SHADER_STAGE_COMPUTE_BIT
	};

	using ShaderStages = vk::Flags<ShaderStage>;
}
