name: Linux Build

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3

      - name: Initialize LFS
        run: |
          git lfs install

      - name: Load submodules
        run: |
          git submodule init
          git submodule update

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install libvulkan-dev libvulkan1

      - name: Build framework
        run: |
          mkdir build
          cd build
          cmake ..
          make -j $(nproc)